packages:
  - .

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: true

overrides:
  yaml: 2.9.0

pnpm:
  autoInstallPeers: true
  strictPeerDependencies: false
  packageImportMethod: clone-or-copy
