const UK_SIGNALS = [
  "united kingdom",
  "northern ireland",
  "met police",
  "metropolitan police",
  "british transport police",
  "police scotland",
  "city of london police",
  "west midlands police",
  "greater manchester police",
  "merseyside police",
  "evening standard",
  "my london",
  "mylondon",
  "manchester evening news",
  "oxford street",
  "covent garden",
  "britain",
  "british",
  "england",
  "scotland",
  "wales",
  "london",
  "westminster",
  "camden",
  "shoreditch",
  "soho",
  "brixton",
  "clapham",
  "hackney",
  "islington",
  "piccadilly",
  "kensington",
  "chelsea",
  "manchester",
  "birmingham",
  "liverpool",
  "glasgow",
  "edinburgh",
  "bristol",
  "leeds",
  "sheffield",
  // Regional towns, counties, and outlet names — without these, legitimate
  // UK stories ("Sussex film", "Yorkshire theft map") failed the geo check.
  "newcastle",
  "sunderland",
  "middlesbrough",
  "tyneside",
  "yorkshire",
  "harrogate",
  "bradford",
  "wakefield",
  "hull",
  "nottingham",
  "leicester",
  "derby",
  "coventry",
  "wolverhampton",
  "smethwick",
  "walsall",
  "stoke",
  "northampton",
  "milton keynes",
  "luton",
  "bedford",
  "peterborough",
  "norwich",
  "ipswich",
  "norfolk",
  "suffolk",
  "cambridge",
  "oxford",
  "reading",
  "brighton",
  "hove",
  "sussex",
  "kent",
  "canterbury",
  "maidstone",
  "southampton",
  "portsmouth",
  "bournemouth",
  "poole",
  "dorset",
  "plymouth",
  "exeter",
  "torbay",
  "newton abbot",
  "cornwall",
  "somerset",
  "bath",
  "gloucester",
  "cheltenham",
  "swindon",
  "wiltshire",
  "devon",
  "horsham",
  "guildford",
  "surrey",
  "hampshire",
  "cumbria",
  "kendal",
  "carlisle",
  "lancaster",
  "preston",
  "blackpool",
  "lancashire",
  "chester",
  "warrington",
  "hertfordshire",
  "watford",
  "essex",
  "chelmsford",
  "southend",
  "cardiff",
  "swansea",
  "newport",
  "wrexham",
  "south wales",
  "north wales",
  "belfast",
  "aberdeen",
  "dundee",
  "inverness",
  "stirling",
  "paisley",
  "fife",
  "perth",
  "ayr",
  "dumfries",
  // UK outlet names — feed titles carry the outlet as a suffix ("- The Mirror"),
  // and a UK outlet reporting unnamed-place crime is almost always UK news.
  // Deliberately excludes generic names (The Times, The Sun, The National).
  "bbc",
  "itv",
  "itvx",
  "sky news",
  "gb news",
  "lbc",
  "channel 4",
  "the telegraph",
  "the mirror",
  "daily mirror",
  "daily express",
  "daily star",
  "daily record",
  "the guardian",
  "the independent",
  "inews",
  "evening standard",
  "mylondon",
  "birmingham live",
  "liverpool echo",
  "manchester evening news",
  "walesonline",
  "yorkshire live",
  "edp24",
  "south wales argus",
  "express and star",
  "sussexworld",
  "bournemouth echo",
  "torbay weekly",
  "nw mail",
  "kent online",
  "get surrey",
  "cambridgeshire live",
  "lancs live",
  "chronicle live",
  "glasgow live",
  "edinburgh live",
  "belfast live",
  "hull live",
  "stoke sentinel",
  "derbyshire times",
  "martin lewis",
  "the sun",
  "eastleigh",
  "londoners",
  "revolut",
  "u.k.",
  "uk",
];

const FOREIGN_SIGNALS = [
  "kakinada",
  "mumbai",
  "delhi",
  "hyderabad",
  "bengaluru",
  "bangalore",
  "chennai",
  "kolkata",
  "kerala",
  "kozhikode",
  "goa",
  "bicholim",
  "pune",
  "jaipur",
  "ajmer",
  "lucknow",
  "patna",
  "puri",
  "konkan",
  "fulbari",
  "andaman",
  "nairobi",
  "kisumu",
  "bungoma",
  "mombasa",
  "likoni",
  "kimilili",
  "kasarani",
  "kenyan",
  "kampala",
  "uganda",
  "lagos",
  "abuja",
  "accra",
  "islamabad",
  "karachi",
  "lahore",
  "dhaka",
  "bangladesh",
  "philippines",
  "manila",
  "australia",
  "sydney",
  "melbourne",
  "auckland",
  "united states",
  "new york",
  "california",
  "los angeles",
  "san francisco",
  "chicago",
  "boston",
  "miami",
  "toronto",
  "vancouver",
  "montreal",
  "mexico",
  "south africa",
  "johannesburg",
  "dublin",
  "ireland",
  "irish",
  "gardai",
  "gardaí",
  "tenerife",
  "mallorca",
  "palma",
  "spain",
  "dubai",
  "singapore",
  "hong kong",
  "jakarta",
  "bangkok",
  "cairo",
  "india",
  "indian",
  "nigeria",
  "kenya",
  "pakistan",
  "canada",
  "brazil",
];

const JUNK_EXCERPT = [
  '{"@context"',
  "this content is provided by",
  "exco player",
  "allow and continue",
  "may use cookies or similar",
];

function hasSignal(blob: string, signal: string): boolean {
  if (signal.includes(" ") || signal.includes(".")) {
    return blob.includes(signal);
  }
  const escaped = signal.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  return new RegExp(`\\b${escaped}\\b`, "i").test(blob);
}

export function sanitizeNewsExcerpt(excerpt: string | undefined, fallback = ""): string {
  if (!excerpt) return fallback;
  let text = excerpt.replace(/\{"@context"[\s\S]*/, "").trim();
  const lower = text.toLowerCase();
  if (JUNK_EXCERPT.some((s) => lower.includes(s))) {
    return fallback;
  }
  return text;
}

export function isUkPhoneTheftStory(input: {
  title: string;
  excerpt?: string;
  sourceUrl?: string;
  sourceName?: string;
}): boolean {
  // Foreign check looks at title + outlet only: a story *about* foreign crime
  // names the place in its headline, while a UK story merely mentioning a
  // trafficking destination ("stolen phones shipped to Nigeria") keeps its UK
  // headline. Checking the excerpt would false-positive on the latter.
  const headline = [input.title, input.sourceUrl ?? "", input.sourceName ?? ""]
    .join(" ")
    .toLowerCase();
  const blob = `${headline} ${input.excerpt ?? ""}`;

  if (FOREIGN_SIGNALS.some((s) => hasSignal(headline, s))) return false;
  if (JUNK_EXCERPT.some((s) => blob.includes(s))) return false;
  return UK_SIGNALS.some((s) => hasSignal(blob, s));
}
